services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=education'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=applicationuser'
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: